service: domains

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

  environment:
    dynamoTableName: ${opt:stage}-domains
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.dynamoTableName}"

package:
  include:
    - get.js
    - put.js
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  domainget:
    handler: get.domainget
    events:
      - http:
          path: domains
          method: get
  domainput:
    handler: put.domainput
    events:
      - http:
          path: domains
          method: put

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${opt:stage}-domains
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1